"""empty message

Revision ID: b177e0dff464
Revises: fe0572a303c1
Create Date: 2017-08-16 16:49:58.904412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b177e0dff464'
down_revision = 'fe0572a303c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pull_request', sa.Column('comment_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pull_request', 'comment_url')
    # ### end Alembic commands ###
